### ISSUE TITLE
Support Firefox!

### ISSUE THREAD

**Issue by nightkr** [teozkr/klocka#4]
Apparently, according to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Push_API/Using_the_Push_API), Firefox requires some kind of encryption scheme in order to work. That makes it a bit more complicated, since we also need to store the key somehow. Hmm...

**Comment by ghost** [comment]
Hi! Sorry for the drive-by. I help work on push at Mozilla; @overholt pointed me to your project. The demo is cool; it's awesome that you got this to work!

The encryption scheme is tricky to implement. You might have already seen this, but Google has a [nice write-up](https://developers.google.com/web/updates/2016/03/web-push-encryption) that goes into the details. @marco-c is working on libraries for Python, PHP, and Node; there isn't a Rust one yet.

AFAIK, Chrome makes encryption [mandatory](https://bugs.chromium.org/p/chromium/issues/detail?id=486040), too, unless you're sending a data-free "ping". It sounds like you were able to send an unencrypted message to Chrome, though?

At first glance, it looks like a ping could work for you: you're sending a [payload to GCM](https://github.com/teozkr/klocka/blob/14f73a988ccfc1db8f3d31b75d8b1f513eb7779f/server/src/action/gcm.rs#L53-L55), but the `push` event listener in your service worker doesn't seem to use `ev.data`. (Unfortunately, Firefox doesn't support `sound` or `requireInteraction` yet; that might be another obstacle).

Cheers!

**Comment by nightkr** [comment]
@kitcambridge I'm just sending a ping, but didn't see anything in the docs that implied that that would be any different. That might just be me being blind, though. From what I was able to tell, Chrome just ignored the payload, which is fine for this use-case.

So I guess the proper thing to do would be to remove the payload completely?

**Comment by ghost** [comment]
> I'm just sending a ping, but didn't see anything in the docs that implied that that would be any different. That might just be me being blind, though. From what I was able to tell, Chrome just ignored the payload, which is fine for this use-case.

The docs do seem a bit vague...the write-up says "all payload data must be encrypted", but it doesn't say what happens if you send unencrypted (or malformed) data. Chrome's behavior makes sense, though. Thanks for clarifying!

> So I guess the proper thing to do would be to remove the payload completely?

I think that's the way to go. Firefox is less forgiving than Chrome in that regard; it'll drop messages without firing the `push` event if it can't decrypt them.

**Comment by nightkr** [comment]
Alright, I'll give it a shot, thanks!

**Comment by nightkr** [comment]
Hm, removing the notification payload doesn't seem to have made much of a difference. Or did you mean that I should just send a completely blank POST?

**Comment by ghost** [comment]
> Or did you mean that I should just send a completely blank POST?

Sorry, my bad. Yes, I meant a completely blank POST for Firefox.

**Comment by nightkr** [comment]
That worked, thanks!

**Comment by ghost** [comment]
Awesome, thank you! ⭐
